Ext.define('PersonApp.model.PersonSearch', {
    extend: 'Ext.data.Model',
    fields: [
        'id',
        'autoGenerated',
        'snils',
        'firstName',
        'middleName',
        'lastName',
        'birthdayFrom',
        'birthdayTo',
        'registrAdress',
        'livingAdress',
        'passportNum1',
        'passportNum2',
        'passportIssuePlace',
        'passportIssueDateFrom',
        'passportIssueDateTo',
        'invalidGroup'
    ]
});