Ext.define('PersonApp.model.Person', {
    extend: 'Ext.data.Model',
    fields: [
        'id',
        //'autoGenerated',
        //'snils',
        //'snilsDate',
        'firstName',
        //'middleName',
        'lastName',
        'birthday'
        //'passportNum1',
        //'passportNum2',
        //'passportIssuePlace',
        //'passportIssueDate',
        //'registrAdress',
        //'livingAdress',
        //'education',
        //'marryage',
        //'socialStat',
        //'job',
        //'pensionType',
        //'invalidGroup'
    ]
});