Ext.define('PersonApp.view.PersonList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.personlist',

    title: 'Регистр',
    store: 'PersonStore',

    initComponent: function () {
        this.columns = [
            { header: 'Id', dataIndex: 'id', flex: 1 },
            { header: 'Name', dataIndex: 'firstName', flex: 1 },
            { header: 'Lastname', dataIndex: 'lastName', flex: 1 },
            { header: 'birth', dataIndex: 'birthday', flex: 1 }
        ];

        this.callParent(arguments);
    }
});



//Ext.define('Person.view.PersonList', {
//    extend: 'Ext.grid.Panel',
//    alias: 'widget.personlist',

//    requires: ['PersonApp.store.PersonStore'],

//    title: 'Регистр граждан',
//    //store: 'PersonStore',
//   // store: 'Person.store.PersonStore',

//    initComponent: function () {
//        debugger;
//        var me = this;

//        me.store = Ext.create('PersonApp.store.PersonStore');


//        me.columns = [
//            { xtype: 'gridcolumn', header: 'Id', dataIndex: 'id', flex: 1 },
//            { xtype: 'gridcolumn', header: 'Name', dataIndex: 'firstName', flex: 1 },
//            { xtype: 'gridcolumn', header: 'Lastname', dataIndex: 'lastName', flex: 1 },
//            { xtype: 'gridcolumn', header: 'Id', dataIndex: 'birthday', flex: 1 }
//        ];

//        this.callParent(arguments);
//    }
//});

//'id',
//    'autoGenerated',
//    'snils',
//    'snilsDate',
//    'firstName',
//    'middleName',
//    'lastName',
//    'birthday',
//    'passportNum1',
//    'passportNum2',
//    'passportIssuePlace',
//    'passportIssueDate',
//    'registrAdress',
//    'livingAdress',
//    'education',
//    'marryage',
//    'socialStat',
//    'job',
//    'pensionType',
//    'invalidGroup']