Ext.define('PersonApp.view.PersonList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.personlist',

    title: 'Регистр',
    store: 'PersonApp.store.PersonStore',

    initComponent: function () {
        //var me = this;
        //me.store = Ext.create('PersonApp.store.PersonStore');
        this.columns = [
            { header: 'ID', dataIndex: 'id', width: 40},
            { header: 'ФИО', xtype: 'templatecolumn', dataIndex: 'firstName', flex: 1, tpl: '<t> {lastName} {firstName} {middleName} </t>'},
            { header: 'Дата рождения', dataIndex: 'birthday', xtype: 'datecolumn', format: 'd:m:Y',  flex: 1 },
            { header: 'Паспорт', xtype: 'templatecolumn', dataIndex: 'passportNum1', flex: 1, tpl: ' ({passportNum1}) {passportNum2} {passportIssuePlace}, Дата выдачи: {passportIssueDate}' },
            { header: 'Адрес', dataIndex: 'livingAdress', flex: 1 }
        ];
        this.callParent(arguments);
    }
});





//'id',
//    'autoGenerated',
//    'snils',
//    'snilsDate',
//    'firstName',
//    'middleName',
//    'lastName',
//    'birthday',
//    'passportNum1',
//    'passportNum2',
//    'passportIssuePlace',
//    'passportIssueDate',
//    'registrAdress',
//    'livingAdress',
//    'education',
//    'marryage',
//    'socialStat',
//    'job',
//    'pensionType',
//    'invalidGroup']