using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BarsTest.Models
{
    public class Person
    {
        public  Person(int Perid, string firstName, string lastName, int birthday)
        {
            this.birthday = birthday;
            this.id = Perid;
            this.lastName = lastName;
            this.firstName = firstName;
        }
        public Person()
        { }
        //[Display(Name = "Id гражданина")]
        public int id { get; set; }
        //public bool? autoGenerated { get; set; }

        //public string Snils { get; set; }
        //public string SnilsDate { get; set; }

        public string firstName { get; set; }
        //public string middleName { get; set; }
        public string lastName { get; set; }
        public int birthday { get; set; }

        //public int? passportNum1 { get; set; }
        //public int? passportNum2 { get; set; }
        //public string passportIssuePlace { get; set; }
        //public string passportIssueDate { get; set; }

        //public string registrAdress { get; set; }
        //public string livingAdress { get; set; }
        //public string education { get; set; }
        //public bool? marryage { get; set; }

        //public string SocialStat { get; set; }
        //public string Job { get; set; }
        //public string PensionType { get; set; }
        //public int? InvalidGroup { get; set; }
    }
}