using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BarsTest.Models
{
    public class Person
    {
        
        

        [Display(Name = "Id гражданина")]
        public int id { get; set; }
        public bool? autoGenerated { get; set; }

        public string Snils { get; set; }
        public DateTime? SnilsDate { get; set; }

        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public DateTime? birthday { get; set; }

        public int? passportNum1 { get; set; }
        public int? passportNum2 { get; set; }
        public string passportIssuePlace { get; set; }
        public DateTime? passportIssueDate { get; set; }

        public string registrAddress { get; set; }
        public string livingAddress { get; set; }
        public string education { get; set; }
        public string maritalstatus { get; set; }

        public string SocialStat { get; set; }
        public string Job { get; set; }
        public string PensionType { get; set; }
        public int? InvalidGroup { get; set; }
    }
}